spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/attendance?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  security:
    basic:
      enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8085


